### ISSUE TITLE
Why ATSAME70 PACs?

### ISSUE THREAD

**Issue by michalfita** [atsam-rs/atsam-pac#25]
May I ask why you compete with [`atsams-rs`](https://github.com/atsams-rs) in publishing PAC crates for ATSAME70 series? We have matching HAL implementations from all SAMS70, SAME70, SAMV70 & SAMV71 and we publish PACs quite regularly.

Wouldn't be better to join us in efforts to maintain them?

**Comment by haata** [comment]
@john-terrell will have to comment but I believe there were any entries in crates.io at the time.

```
git log atsame70j19

commit 4722924c4efc351b8a19491aecf4ba0edc14d50b
Author: John W. Terrell <john@coolpeoplenetworks.com>
Date:   Mon Apr 12 22:04:31 2021 -0700

    John/same70 support (#19)

    * Added SVDs for ATSAME70

    * SAME70 Support

    * README Update to include E70 parts.
(END)
```

https://crates.io/crates/atsame70j19-pac/versions vs. https://crates.io/crates/atsame70j19/versions

At the time @john-terrell had some custom patches to svd2rust to make a bunch of these pacs even generate (which have all since been upstreamed).

Anyways, neither I or @john-terrell have done much with the SAME support  (afaik), so would you prefer to take ownership of this crate instead? Or should we just deprecate it?

**Comment by michalfita** [comment]
Thanks for the reply, @haata. I don't mind either, but because yours have already version higher that ours we can't publish anything until we get there. So, ideally would be if you release with deprecation note and link to our crates, if you don't mind. If you pass ownership, I may do the same (crates.io do not have aliases for crate names to switch).

**Comment by michalfita** [comment]
https://crates.io/crates/atsame70j19b/versions is actually the right link - and first version predates yours. The reason for letter "B" is that actual revision of these chips according to Atmel/Microchip are "B" and there were boards in circulation with "A" revision.

**Comment by michalfita** [comment]
Plus, you may be interested in this tool: https://crates.io/crates/atpacks-svd-harvester

**Comment by haata** [comment]
Sorry for the delay. I've yanked all the atsame7 crates so it should no longer cause confusion. I've also put a link in the README.md to point to your crate.
